# https://travis-ci.org/kanasimi/CeJS
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# http://lint.travis-ci.org/
language: node_js
node_js:
# FreeBSD ports node-devel
# But it seems problems at v8 engine of Travis CI when running CeL.value_of()?
# @see https://travis-ci.org/kanasimi/CeJS/jobs/86175787
# @see https://ci.appveyor.com/project/kanasimi/cejs/build/job/co0jl2uj6r1m4ex8
# It's OK at my FreeBSD under node.js v0.11.16.
#  - "0.11"

# Wikimedia Tool Labs: v0.10.25
# Travis CI gets "CERT_UNTRUSTED" on node.js 0.10.25 after 2016/10/15. Stop the version temporarily.
# https://thequietinnovator.com/2015/10/11/how-to-fix-nodejs-cert_untrusted-issues/
#  - "0.10.25"
  - "0.10"

# 2016/10/23: Travis CI failed on node.js 0.11
#  - "0.11"

#  - "0.12"
  - "4"
#  - "4.1"
  - "6"

install:
  - npm install
